-- PostGIS schema generated by ps.editor.actions from the feature catalogue.
-- Structure only: no data apart from code-list values.

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS "administrative_enheter";

CREATE TABLE "administrative_enheter"."kommunenummer" (
  "identifier" text PRIMARY KEY,
  "description" text
);
INSERT INTO "administrative_enheter"."kommunenummer" ("identifier", "description") VALUES
  ('1875', 'Hábmer – Hamarøy'),
  ('3205', 'Lillestrøm'),
  ('4205', 'Lindesnes'),
  ('3124', 'Aremark'),
  ('3310', 'Hole'),
  ('4018', 'Nome'),
  ('3443', 'Vestre Toten'),
  ('1101', 'Eigersund'),
  ('4630', 'Osterøy'),
  ('4225', 'Lyngdal'),
  ('5035', 'Stjørdal'),
  ('4642', 'Lærdal'),
  ('1114', 'Bjerkreim'),
  ('5043', 'Raarvikhe – Røyrvik'),
  ('3122', 'Marker'),
  ('1838', 'Gildeskål'),
  ('4647', 'Sunnfjord'),
  ('4651', 'Stryn'),
  ('5538', 'Storfjord - Omasvuotna - Omasvuono'),
  ('4626', 'Øygarden'),
  ('5618', 'Måsøy'),
  ('3330', 'Hol'),
  ('4034', 'Tokke'),
  ('5055', 'Heim'),
  ('1528', 'Sykkylven'),
  ('3436', 'Nord-Fron'),
  ('4637', 'Hyllestad'),
  ('3114', 'Våler'),
  ('4644', 'Luster'),
  ('3414', 'Nord-Odal'),
  ('1827', 'Dønna'),
  ('1560', 'Tingvoll'),
  ('3449', 'Sør-Aurdal'),
  ('5614', 'Loppa'),
  ('3230', 'Gjerdrum'),
  ('1866', 'Hadsel'),
  ('5027', 'Midtre Gauldal'),
  ('3103', 'Moss'),
  ('5046', 'Høylandet'),
  ('3425', 'Engerdal'),
  ('3423', 'Stor-Elvdal'),
  ('4645', 'Askvoll'),
  ('3422', 'Åmot'),
  ('3439', 'Ringebu'),
  ('4024', 'Hjartdal'),
  ('4639', 'Vik'),
  ('5510', 'Kvæfjord'),
  ('1578', 'Fjord'),
  ('3236', 'Jevnaker'),
  ('3224', 'Rælingen'),
  ('5022', 'Rennebu'),
  ('3911', 'Færder'),
  ('3909', 'Larvik'),
  ('3905', 'Tønsberg'),
  ('3216', 'Vestby'),
  ('3107', 'Fredrikstad'),
  ('4005', 'Notodden'),
  ('3415', 'Sør-Odal'),
  ('4227', 'Kvinesdal'),
  ('1515', 'Herøy i Møre og Romsdal'),
  ('1845', 'Sørfold'),
  ('1867', 'Bø i Nordland'),
  ('3120', 'Rakkestad'),
  ('3454', 'Vang'),
  ('3403', 'Hamar'),
  ('2100', 'Svalbard'),
  ('5041', 'Snåase – Snåsa'),
  ('1106', 'Haugesund'),
  ('3305', 'Ringerike'),
  ('5524', 'Målselv'),
  ('1511', 'Vanylven'),
  ('1579', 'Hustadvika'),
  ('4216', 'Birkenes'),
  ('1856', 'Røst'),
  ('3453', 'Øystre Slidre'),
  ('3110', 'Hvaler'),
  ('1811', 'Bindal'),
  ('3405', 'Lillehammer'),
  ('5038', 'Verdal'),
  ('4641', 'Aurland'),
  ('2211', 'Jan Mayen'),
  ('1122', 'Gjesdal'),
  ('3322', 'Nesbyen'),
  ('1815', 'Vega'),
  ('5622', 'Porsanger - Porsáŋgu - Porsanki'),
  ('3421', 'Trysil'),
  ('4001', 'Porsgrunn'),
  ('5520', 'Bardu'),
  ('4219', 'Evje og Hornnes'),
  ('5540', 'Gáivuotna - Kåfjord - Kaivuono'),
  ('4202', 'Grimstad'),
  ('4028', 'Kviteseid'),
  ('3429', 'Folldal'),
  ('5021', 'Oppdal'),
  ('4621', 'Voss'),
  ('5045', 'Grong'),
  ('4643', 'Årdal'),
  ('1134', 'Suldal'),
  ('3238', 'Nannestad'),
  ('1563', 'Sunndal'),
  ('4615', 'Fitjar'),
  ('4640', 'Sogndal'),
  ('1557', 'Gjemnes'),
  ('3450', 'Etnedal'),
  ('5516', 'Gratangen'),
  ('5546', 'Kvænangen'),
  ('3220', 'Enebakk'),
  ('1516', 'Ulstein'),
  ('3417', 'Grue'),
  ('4020', 'Midt-Telemark'),
  ('4010', 'Siljan'),
  ('4634', 'Masfjorden'),
  ('4623', 'Samnanger'),
  ('3440', 'Øyer'),
  ('1841', 'Fauske – Fuossko'),
  ('3435', 'Vågå'),
  ('3218', 'Ås'),
  ('5042', 'Lierne'),
  ('1868', 'Øksnes'),
  ('1871', 'Andøy'),
  ('1120', 'Klepp'),
  ('1566', 'Surnadal'),
  ('5522', 'Salangen'),
  ('1859', 'Flakstad'),
  ('3242', 'Hurdal'),
  ('3433', 'Skjåk'),
  ('5624', 'Lebesby'),
  ('3324', 'Gol'),
  ('5028', 'Melhus'),
  ('4032', 'Fyresdal'),
  ('4207', 'Flekkefjord'),
  ('5047', 'Overhalla'),
  ('5636', 'Unjárga - Nesseby'),
  ('4636', 'Solund'),
  ('1146', 'Tysvær'),
  ('4022', 'Seljord'),
  ('1121', 'Time'),
  ('1857', 'Værøy'),
  ('3447', 'Søndre Land'),
  ('5060', 'Nærøysund'),
  ('1870', 'Sortland – Suortá'),
  ('4619', 'Eidfjord'),
  ('3207', 'Nordre Follo'),
  ('1848', 'Steigen'),
  ('1822', 'Leirfjord'),
  ('1160', 'Vindafjord'),
  ('1816', 'Vevelstad'),
  ('4646', 'Fjaler'),
  ('5054', 'Indre Fosen'),
  ('3407', 'Gjøvik'),
  ('1832', 'Hemnes'),
  ('5616', 'Hasvik'),
  ('1505', 'Kristiansund'),
  ('1547', 'Aukra'),
  ('3214', 'Frogn'),
  ('1124', 'Sola'),
  ('1145', 'Bokn'),
  ('1103', 'Stavanger'),
  ('5056', 'Hitra'),
  ('1506', 'Molde'),
  ('1119', 'Hå'),
  ('3234', 'Lunner'),
  ('1532', 'Giske'),
  ('3442', 'Østre Toten'),
  ('4628', 'Vaksdal'),
  ('4228', 'Sirdal'),
  ('4220', 'Bygland'),
  ('4222', 'Bykle'),
  ('3428', 'Alvdal'),
  ('3209', 'Ullensaker'),
  ('3427', 'Tynset'),
  ('1149', 'Karmøy'),
  ('1840', 'Saltdal'),
  ('4614', 'Stord'),
  ('1580', 'Haram'),
  ('3903', 'Holmestrand'),
  ('4030', 'Nissedal'),
  ('0301', 'Oslo'),
  ('5025', 'Rosse – Røros'),
  ('3416', 'Eidskog'),
  ('5036', 'Frosta'),
  ('4223', 'Vennesla'),
  ('5049', 'Flatanger'),
  ('4629', 'Modalen'),
  ('4601', 'Bergen'),
  ('5057', 'Ørland'),
  ('3228', 'Nes'),
  ('3232', 'Nittedal'),
  ('3446', 'Gran'),
  ('4622', 'Kvam'),
  ('1151', 'Utsira'),
  ('1127', 'Randaberg'),
  ('1853', 'Evenes – Evenášši'),
  ('5058', 'Åfjord'),
  ('1539', 'Rauma'),
  ('4627', 'Askøy'),
  ('3411', 'Ringsaker'),
  ('5061', 'Rindal'),
  ('5020', 'Osen'),
  ('5544', 'Nordreisa - Ráisa - Raisi'),
  ('1824', 'Vefsn'),
  ('3424', 'Rendalen'),
  ('4203', 'Arendal'),
  ('3401', 'Kongsvinger'),
  ('4617', 'Kvinnherad'),
  ('5029', 'Skaun'),
  ('1825', 'Grane'),
  ('4625', 'Austevoll'),
  ('5514', 'Ibestad'),
  ('1837', 'Meløy'),
  ('4649', 'Stad'),
  ('5037', 'Levanger'),
  ('4613', 'Bømlo'),
  ('5620', 'Nordkapp'),
  ('4633', 'Fedje'),
  ('3326', 'Hemsedal'),
  ('5632', 'Båtsfjord'),
  ('1834', 'Lurøy'),
  ('4213', 'Tvedestrand'),
  ('4632', 'Austrheim'),
  ('5053', 'Inderøy'),
  ('5032', 'Selbu'),
  ('4201', 'Risør'),
  ('3312', 'Lier'),
  ('4616', 'Tysnes'),
  ('1517', 'Hareid'),
  ('4631', 'Alver'),
  ('3437', 'Sel'),
  ('4016', 'Drangedal'),
  ('3105', 'Sarpsborg'),
  ('1508', 'Ålesund'),
  ('4206', 'Farsund'),
  ('5626', 'Gamvik'),
  ('5512', 'Tjeldsund - Dielddanuorri'),
  ('5501', 'Tromsø'),
  ('1573', 'Smøla'),
  ('5536', 'Lyngen'),
  ('3431', 'Dovre'),
  ('1535', 'Vestnes'),
  ('3328', 'Ål'),
  ('3430', 'Os'),
  ('4612', 'Sveio'),
  ('3203', 'Asker'),
  ('1836', 'Rødøy'),
  ('3452', 'Vestre Slidre'),
  ('5014', 'Frøya'),
  ('4638', 'Høyanger'),
  ('1818', 'Herøy i Nordland'),
  ('3314', 'Øvre Eiker'),
  ('4036', 'Vinje'),
  ('5526', 'Sørreisa'),
  ('1812', 'Sømna'),
  ('1828', 'Nesna'),
  ('5007', 'Namsos – Nåavmesjenjaelmie'),
  ('4026', 'Tinn'),
  ('3112', 'Råde'),
  ('4014', 'Kragerø'),
  ('1813', 'Brønnøy'),
  ('1554', 'Averøy'),
  ('3420', 'Elverum'),
  ('4650', 'Gloppen'),
  ('4212', 'Vegårshei'),
  ('3101', 'Halden'),
  ('3334', 'Flesberg'),
  ('1112', 'Lund'),
  ('1804', 'Bodø'),
  ('3212', 'Nesodden'),
  ('1111', 'Sokndal'),
  ('3336', 'Rollag'),
  ('3412', 'Løten'),
  ('4602', 'Kinn'),
  ('3438', 'Sør-Fron'),
  ('3318', 'Krødsherad'),
  ('3301', 'Drammen'),
  ('5634', 'Vardø'),
  ('5605', 'Sør-Varanger'),
  ('5518', 'Loabák - Lavangen'),
  ('1135', 'Sauda'),
  ('4012', 'Bamble'),
  ('1874', 'Moskenes'),
  ('3901', 'Horten'),
  ('5628', 'Deatnu - Tana'),
  ('3226', 'Aurskog-Høland'),
  ('4003', 'Skien'),
  ('5528', 'Dyrøy'),
  ('5031', 'Malvik'),
  ('4624', 'Bjørnafjorden'),
  ('3432', 'Lesja'),
  ('5612', 'Guovdageaidnu - Kautokeino'),
  ('5532', 'Balsfjord'),
  ('4204', 'Kristiansand'),
  ('5530', 'Senja'),
  ('1133', 'Hjelmeland'),
  ('1820', 'Alstahaug'),
  ('1826', 'Aarborte – Hattfjelldal'),
  ('4618', 'Ullensvang'),
  ('4635', 'Gulen'),
  ('4620', 'Ulvik'),
  ('1514', 'Sande i Møre og Romsdal'),
  ('4217', 'Åmli'),
  ('3419', 'Våler i Innlandet'),
  ('1531', 'Sula'),
  ('1144', 'Kvitsøy'),
  ('5006', 'Steinkjer'),
  ('5534', 'Karlsøy'),
  ('1851', 'Lødingen'),
  ('5052', 'Leka'),
  ('4221', 'Valle'),
  ('5044', 'Namsskogan'),
  ('3426', 'Tolga'),
  ('5607', 'Vadsø'),
  ('3332', 'Sigdal'),
  ('5033', 'Tydal'),
  ('3320', 'Flå'),
  ('3222', 'Lørenskog'),
  ('5610', 'Kárášjohka - Karasjok'),
  ('5034', 'Meråker'),
  ('4218', 'Iveland'),
  ('4226', 'Hægebostad'),
  ('1835', 'Træna'),
  ('5601', 'Alta'),
  ('4211', 'Gjerstad'),
  ('5630', 'Berlevåg'),
  ('1577', 'Volda'),
  ('1576', 'Aure'),
  ('1806', 'Narvik'),
  ('1108', 'Sandnes'),
  ('1130', 'Strand'),
  ('3338', 'Nore og Uvdal'),
  ('3116', 'Skiptvet'),
  ('3303', 'Kongsberg'),
  ('3441', 'Gausdal'),
  ('3451', 'Nord-Aurdal'),
  ('3316', 'Modum'),
  ('4648', 'Bremanger'),
  ('1839', 'Beiarn'),
  ('3240', 'Eidsvoll'),
  ('3448', 'Nordre Land'),
  ('1833', 'Rana'),
  ('5001', 'Trondheim – Tråante'),
  ('1525', 'Stranda'),
  ('3434', 'Lom'),
  ('4224', 'Åseral'),
  ('1860', 'Vestvågøy'),
  ('4214', 'Froland'),
  ('3907', 'Sandefjord'),
  ('5503', 'Harstad - Hárstták'),
  ('5059', 'Orkland'),
  ('3413', 'Stange'),
  ('3201', 'Bærum'),
  ('1520', 'Ørsta'),
  ('4215', 'Lillesand'),
  ('5026', 'Holtålen'),
  ('1865', 'Vågan'),
  ('5542', 'Skjervøy'),
  ('4611', 'Etne'),
  ('3118', 'Indre Østfold'),
  ('5603', 'Hammerfest - Hámmerfeasta'),
  ('3418', 'Åsnes');

CREATE TABLE "administrative_enheter"."maalemetode" (
  "identifier" text PRIMARY KEY,
  "description" text
);
INSERT INTO "administrative_enheter"."maalemetode" ("identifier", "description") VALUES
  ('80', 'Frihåndstegning'),
  ('92', 'GNSS: Kodemåling, enkle målinger'),
  ('40', 'Digitaliseringbord: Ortofoto eller flybilde'),
  ('71', 'Spesielle metoder: Målt med stikkstang'),
  ('15', 'Utmål'),
  ('48', 'Digitalisert på skjerm fra tolkning av seismikk'),
  ('82', 'Frihåndstegning på skjerm'),
  ('42', 'Digitaliseringbord: Ortofoto, fotokopi'),
  ('95', 'Kombinasjon av GNSS/Treghet'),
  ('37', 'Bilbåren laser'),
  ('94', 'GNSS: Fasemåling, andre metoder'),
  ('99', 'Ukjent målemetode'),
  ('21', 'Aerotriangulert'),
  ('12', 'Terrengmålt: Teodolitt og el avstandsmåler'),
  ('31', 'Skannet fra kart: Blyantoriginal'),
  ('64', 'Genererte data: Generalisering'),
  ('65', 'Genererte data: Sentralpunkt'),
  ('13', 'Terrengmålt: Teodolitt og målebånd'),
  ('61', 'Genererte data (interpolasjon): Terrengmodell'),
  ('44', 'Digitaliseringbord: Flybilde, fotokopi'),
  ('96', 'GNSS: Fasemåling RTK'),
  ('76', 'Fastsatt'),
  ('46', 'Digitalisert på skjerm fra satellittbilde'),
  ('91', 'GNSS: Kodemåling, relative målinger'),
  ('41', 'Digitaliseringbord: Ortofoto, film'),
  ('50', 'Digitaliseringsbord: Kart'),
  ('72', 'Spesielle metoder: Målt med waterstang'),
  ('33', 'Skannet fra kart: Transparent folie, god kvalitet'),
  ('60', 'Genererte data (interpolasjon)'),
  ('68', 'Koordinater hentet fra JREG'),
  ('73', 'Spesielle metoder: Målt med målehjul'),
  ('19', 'Annet'),
  ('93', 'GNSS: Fasemåling, statisk måling'),
  ('43', 'Digitaliseringbord: Flybilde, film'),
  ('78', 'Fastsatt ved dom eller kongelig resolusjon'),
  ('53', 'Digitaliseringsbord: Kart, transparent foile, god kvalitet'),
  ('70', 'Spesielle metoder'),
  ('30', 'Scannet fra kart'),
  ('36', 'Flybåren laserscanner'),
  ('74', 'Spesielle metoder: Målt med stigningsmåler'),
  ('63', 'Genererte data: Fra annen geometri'),
  ('97', 'GNSS: Fasemåling , float-løsning'),
  ('24', 'Stereoinstrument: Digitalt'),
  ('14', 'Terrengmålt: Ortogonalmetoden'),
  ('18', 'Tatt fra plan'),
  ('49', 'Vektorisering av laserdata'),
  ('54', 'Digitaliseringsbord: Kart, transparent foile, mindre god kvalitet'),
  ('34', 'Skannet fra kart: Transparent folie, mindre god kvalitet'),
  ('35', 'Skannet fra kart: Papirkopi'),
  ('11', 'Terrengmålt: Totalstasjon'),
  ('22', 'Stereoinstrument: Analytisk plotter'),
  ('38', 'Lineær referanse'),
  ('79', 'Annet - spesifiseres i filhode'),
  ('77', 'Fastsatt punkt'),
  ('51', 'Digitaliseringsbord: Kart, blyantoriginal'),
  ('47', 'Digitalisert på skjerm fra andre digitale rasterdata'),
  ('45', 'Digitalisert på skjerm fra ortofoto'),
  ('56', 'Digitalisert på skjerm fra skannet kart'),
  ('66', 'Genererte data: Sammenknytningspunkt, randpunkt'),
  ('32', 'Skannet fra kart: Rissefolie'),
  ('90', 'Treghetsstedfesting'),
  ('81', 'Frihåndstegning på kart'),
  ('20', 'Stereoinstrument'),
  ('62', 'Genererte data (interpolasjon): Vektet middel'),
  ('52', 'Digitaliseringsbord: Kart, rissefoile'),
  ('55', 'Digitaliseringsbord: Kart, papirkopi'),
  ('10', 'Terrengmålt: Uspesifisert måleinstrument'),
  ('67', 'Koordinater hentet fra GAB'),
  ('69', 'Beregnet'),
  ('23', 'Stereoinstrument: Autograf');

CREATE TABLE "administrative_enheter"."typeavgrensning" (
  "identifier" text PRIMARY KEY,
  "description" text
);
INSERT INTO "administrative_enheter"."typeavgrensning" ("identifier", "description") VALUES
  ('Riksgrense', 'avgrensningen av nasjonen Norge på land mot andre nasjoner'),
  ('Territorialgrense', 'avgrensning i havet av statens suverenitetsområde, beregnet 12 nm (22 224 m) utenfor og parallelt med grunnlinjen'),
  ('AvtaltAvgrensningslinje', 'avtalt avgrensningslinje til havs basert på folkerettslig bindende avtaler

Merknad:
Avtalt avgrensningslinje vil normalt gjelde alle aktuelle former for kyststatsjurisdiksjon. Detaljene vil framgå av den aktuelle avgrensningsavtale.

Merknad 2:
Benyttes også som avgrensning av kontinentalsokkel i internasjonalt farvann, der flere stater kan framlegge dokumentasjon om rettigheter til sokkelen, men der statene har kommet til enighet om en avgrensningslinje.'),
  ('Kommunegrense', 'avgrensing av kommune'),
  ('Fylkesgrense', 'avgrensning av fylke'),
  ('Grunnkretsgrense', 'avgrensning av grunnkrets'),
  ('Delområdegrense', 'avgrensning av delområde'),
  ('Stemmekretsgrense', 'avgrensing av Stemmekrets');

CREATE TABLE "administrative_enheter"."fylkesnummer" (
  "identifier" text PRIMARY KEY,
  "description" text
);
INSERT INTO "administrative_enheter"."fylkesnummer" ("identifier", "description") VALUES
  ('34', 'Innlandet'),
  ('46', 'Vestland'),
  ('40', 'Telemark'),
  ('55', 'Troms – Romsa – Tromssa'),
  ('03', 'Oslo'),
  ('11', 'Rogaland'),
  ('42', 'Agder'),
  ('18', 'Nordland – Nordlánnda'),
  ('32', 'Akershus'),
  ('39', 'Vestfold'),
  ('15', 'Møre og Romsdal'),
  ('21', 'Svalbard'),
  ('56', 'Finnmark – Finnmárku – Finmarkku'),
  ('31', 'Østfold'),
  ('33', 'Buskerud'),
  ('22', 'Jan Mayen'),
  ('50', 'Trøndelag – Trööndelage');

CREATE TABLE "administrative_enheter"."spraakkode" (
  "identifier" text PRIMARY KEY,
  "description" text
);
INSERT INTO "administrative_enheter"."spraakkode" ("identifier", "description") VALUES
  ('English', 'English'),
  ('KvenFinnish', 'Kven Finnish'),
  ('LuleSami', 'Lule Sami'),
  ('NorthernSami', 'Northern Sami'),
  ('Swedish', 'Swedish'),
  ('Finnish', 'Finnish'),
  ('Norwegian', 'Norwegian'),
  ('SouthernSami', 'Southern Sami');

CREATE TABLE "administrative_enheter"."kommune" (
  "objid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "objtype" text NOT NULL DEFAULT 'Kommune',
  "identifikasjon_lokalid" text NOT NULL,
  "identifikasjon_navnerom" text NOT NULL,
  "identifikasjon_versjonid" text,
  "oppdateringsdato" timestamp with time zone NOT NULL,
  "gyldigfra" date,
  "gyldigtil" date,
  "datafangstdato" timestamp with time zone,
  "datauttaksdato" timestamp with time zone,
  "opphav" text,
  "omraade" geometry(MultiPolygon, 25833) NOT NULL,
  "kommunenummer" text NOT NULL,
  "kommunenavn" text NOT NULL,
  "samiskforvaltningsomraade" boolean
);

CREATE TABLE "administrative_enheter"."grense" (
  "objid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "objtype" text NOT NULL DEFAULT 'Grense',
  "identifikasjon_lokalid" text NOT NULL,
  "identifikasjon_navnerom" text NOT NULL,
  "identifikasjon_versjonid" text,
  "oppdateringsdato" timestamp with time zone NOT NULL,
  "gyldigfra" date,
  "gyldigtil" date,
  "datafangstdato" timestamp with time zone,
  "kvalitet_maalemetode" text,
  "kvalitet_noeyaktighet" integer,
  "datauttaksdato" timestamp with time zone,
  "opphav" text,
  "grense" geometry(LineString, 25833) NOT NULL,
  "avgrensningstype" text NOT NULL
);

CREATE TABLE "administrative_enheter"."fylke" (
  "objid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "objtype" text NOT NULL DEFAULT 'Fylke',
  "identifikasjon_lokalid" text NOT NULL,
  "identifikasjon_navnerom" text NOT NULL,
  "identifikasjon_versjonid" text,
  "oppdateringsdato" timestamp with time zone NOT NULL,
  "gyldigfra" date,
  "gyldigtil" date,
  "datafangstdato" timestamp with time zone,
  "datauttaksdato" timestamp with time zone,
  "opphav" text,
  "omraade" geometry(MultiPolygon, 25833) NOT NULL,
  "fylkesnummer" text NOT NULL,
  "fylkesnavn" text NOT NULL,
  "samiskforvaltningsomraade" boolean
);

CREATE TABLE "administrative_enheter"."kommune_administrativenhetnavn" (
  "objid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kommune_fk" integer NOT NULL,
  "navn" text NOT NULL,
  "spraak" text NOT NULL,
  "rekkefoelge" integer
);

CREATE TABLE "administrative_enheter"."fylke_administrativenhetnavn" (
  "objid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fylke_fk" integer NOT NULL,
  "navn" text NOT NULL,
  "spraak" text NOT NULL,
  "rekkefoelge" integer
);

CREATE TABLE "administrative_enheter"."kommune_avgrensesavgrense" (
  "objid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kommune_fk" integer NOT NULL,
  "grense_fk" integer NOT NULL,
  CONSTRAINT "kommune_avgrensesavgrense_key" UNIQUE ("kommune_fk", "grense_fk")
);

CREATE TABLE "administrative_enheter"."fylke_avgrensesavgrense" (
  "objid" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fylke_fk" integer NOT NULL,
  "grense_fk" integer NOT NULL,
  CONSTRAINT "fylke_avgrensesavgrense_key" UNIQUE ("fylke_fk", "grense_fk")
);

ALTER TABLE "administrative_enheter"."kommune" ADD CONSTRAINT "kommune_kommunenummer_fkey" FOREIGN KEY ("kommunenummer") REFERENCES "administrative_enheter"."kommunenummer" ("identifier") ON DELETE NO ACTION;
ALTER TABLE "administrative_enheter"."grense" ADD CONSTRAINT "grense_kvalitet_maalemetode_fkey" FOREIGN KEY ("kvalitet_maalemetode") REFERENCES "administrative_enheter"."maalemetode" ("identifier") ON DELETE NO ACTION;
ALTER TABLE "administrative_enheter"."grense" ADD CONSTRAINT "grense_avgrensningstype_fkey" FOREIGN KEY ("avgrensningstype") REFERENCES "administrative_enheter"."typeavgrensning" ("identifier") ON DELETE NO ACTION;
ALTER TABLE "administrative_enheter"."fylke" ADD CONSTRAINT "fylke_fylkesnummer_fkey" FOREIGN KEY ("fylkesnummer") REFERENCES "administrative_enheter"."fylkesnummer" ("identifier") ON DELETE NO ACTION;
ALTER TABLE "administrative_enheter"."kommune_administrativenhetnavn" ADD CONSTRAINT "kommune_administrativenhetnavn_kommune_fk_fkey" FOREIGN KEY ("kommune_fk") REFERENCES "administrative_enheter"."kommune" ("objid") ON DELETE CASCADE;
ALTER TABLE "administrative_enheter"."kommune_administrativenhetnavn" ADD CONSTRAINT "kommune_administrativenhetnavn_spraak_fkey" FOREIGN KEY ("spraak") REFERENCES "administrative_enheter"."spraakkode" ("identifier") ON DELETE NO ACTION;
ALTER TABLE "administrative_enheter"."fylke_administrativenhetnavn" ADD CONSTRAINT "fylke_administrativenhetnavn_fylke_fk_fkey" FOREIGN KEY ("fylke_fk") REFERENCES "administrative_enheter"."fylke" ("objid") ON DELETE CASCADE;
ALTER TABLE "administrative_enheter"."fylke_administrativenhetnavn" ADD CONSTRAINT "fylke_administrativenhetnavn_spraak_fkey" FOREIGN KEY ("spraak") REFERENCES "administrative_enheter"."spraakkode" ("identifier") ON DELETE NO ACTION;
ALTER TABLE "administrative_enheter"."kommune_avgrensesavgrense" ADD CONSTRAINT "kommune_avgrensesavgrense_kommune_fk_fkey" FOREIGN KEY ("kommune_fk") REFERENCES "administrative_enheter"."kommune" ("objid") ON DELETE CASCADE;
ALTER TABLE "administrative_enheter"."kommune_avgrensesavgrense" ADD CONSTRAINT "kommune_avgrensesavgrense_grense_fk_fkey" FOREIGN KEY ("grense_fk") REFERENCES "administrative_enheter"."grense" ("objid") ON DELETE CASCADE;
ALTER TABLE "administrative_enheter"."fylke_avgrensesavgrense" ADD CONSTRAINT "fylke_avgrensesavgrense_fylke_fk_fkey" FOREIGN KEY ("fylke_fk") REFERENCES "administrative_enheter"."fylke" ("objid") ON DELETE CASCADE;
ALTER TABLE "administrative_enheter"."fylke_avgrensesavgrense" ADD CONSTRAINT "fylke_avgrensesavgrense_grense_fk_fkey" FOREIGN KEY ("grense_fk") REFERENCES "administrative_enheter"."grense" ("objid") ON DELETE CASCADE;

CREATE INDEX "kommune_omraade_gist" ON "administrative_enheter"."kommune" USING GIST ("omraade");
CREATE INDEX "grense_grense_gist" ON "administrative_enheter"."grense" USING GIST ("grense");
CREATE INDEX "fylke_omraade_gist" ON "administrative_enheter"."fylke" USING GIST ("omraade");
CREATE INDEX "kommune_kommunenummer_idx" ON "administrative_enheter"."kommune" ("kommunenummer");
CREATE INDEX "grense_kvalitet_maalemetode_idx" ON "administrative_enheter"."grense" ("kvalitet_maalemetode");
CREATE INDEX "grense_avgrensningstype_idx" ON "administrative_enheter"."grense" ("avgrensningstype");
CREATE INDEX "fylke_fylkesnummer_idx" ON "administrative_enheter"."fylke" ("fylkesnummer");
CREATE INDEX "kommune_administrativenhetnavn_kommune_fk_idx" ON "administrative_enheter"."kommune_administrativenhetnavn" ("kommune_fk");
CREATE INDEX "kommune_administrativenhetnavn_spraak_idx" ON "administrative_enheter"."kommune_administrativenhetnavn" ("spraak");
CREATE INDEX "fylke_administrativenhetnavn_fylke_fk_idx" ON "administrative_enheter"."fylke_administrativenhetnavn" ("fylke_fk");
CREATE INDEX "fylke_administrativenhetnavn_spraak_idx" ON "administrative_enheter"."fylke_administrativenhetnavn" ("spraak");
CREATE INDEX "kommune_avgrensesavgrense_grense_fk_idx" ON "administrative_enheter"."kommune_avgrensesavgrense" ("grense_fk");
CREATE INDEX "fylke_avgrensesavgrense_grense_fk_idx" ON "administrative_enheter"."fylke_avgrensesavgrense" ("grense_fk");

COMMENT ON TABLE "administrative_enheter"."kommunenummer" IS '<font color="#333333">nummerering av kommuner i henhold til SSB sin offisielle liste</font>
Merknad: <font color="#333333">Inneholder fremtidige, gyldige og utgåtte kommunenummer. </font>Det presiseres at kommune alltid skal ha 4 sifre, dvs. eventuelt med ledende null. Kommune benyttes for kopling mot en rekke andre registre som også benytter 4 sifre.

<i>URI til ekstern kodeliste:</i> https://register.geonorge.no/sosi-kodelister/kommunenummer?page=2

Kodeliste: https://register.geonorge.no/sosi-kodelister/inndelinger/inndelingsbase/kommunenummer';
COMMENT ON TABLE "administrative_enheter"."maalemetode" IS 'metode som ligger til grunn for registrering av posisjon


-- Definition - -
method on which registration of position is based

Kodeliste: https://register.geonorge.no/sosi-kodelister/generelle-konsepter/4.5/m%C3%A5lemetodekode';
COMMENT ON TABLE "administrative_enheter"."typeavgrensning" IS 'oversikt over ulike typer avgrensingslinjer.';
COMMENT ON TABLE "administrative_enheter"."fylkesnummer" IS 'nummerering av fylker <font color="#333333"> </font>
<font color="#333333">
</font><font color="#333333">Merknad: Inneholder fremtidige, gyldige og utgåtte nummer. Fylket skal alltid ha 2 sifre, dvs. eventuelt med ledende null.</font>
<i>URI til ekstern kodeliste:</i> https://register.geonorge.no/sosi-kodelister/inndelinger/inndelingsbase/fylkesnummer

Kodeliste: https://register.geonorge.no/sosi-kodelister/inndelinger/inndelingsbase/fylkesnummer?';
COMMENT ON TABLE "administrative_enheter"."spraakkode" IS 'ISO 639 del 3 språkkodetabell

Merknad: ufullstendig kodeliste pga. importfeil

language code tables of ISO 639 part 3

ISO 639-3 is a code that aims to define three-letter identifiers for all known human languages. At the core of ISO 639-3 are the individual languages already accounted for in ISO 639-2.';
COMMENT ON TABLE "administrative_enheter"."kommune" IS 'inndeling i administrative og politiske enheter innenfor fylket

Merknad: Tilsvarer NUTS 5 og LAU 2 på internasjonalt statistisk nivå';
COMMENT ON COLUMN "administrative_enheter"."kommune"."identifikasjon_lokalid" IS 'lokal identifikator av et objekt

Merknad: Det er dataleverandørens ansvar å sørge for at den lokale identifikatoren er unik innenfor navnerommet.';
COMMENT ON COLUMN "administrative_enheter"."kommune"."identifikasjon_navnerom" IS 'navnerom som unikt identifiserer datakilden til et objekt, anbefales å være en http-URI

Eksempel: http://data.geonorge.no/SentraltStedsnavnsregister/1.0

Merknad : Verdien for navnerom vil eies av den dataprodusent som har ansvar for de unike identifikatorene og må være registrert i data.geonorge.no eller data.norge.no';
COMMENT ON COLUMN "administrative_enheter"."kommune"."identifikasjon_versjonid" IS 'identifikasjon av en spesiell versjon av et geografisk objekt (instans)';
COMMENT ON COLUMN "administrative_enheter"."kommune"."oppdateringsdato" IS 'tidspunkt for siste endring på objektet

Merknad:
Oppdateringsdato kan være forskjellig fra datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).';
COMMENT ON COLUMN "administrative_enheter"."kommune"."gyldigfra" IS 'Tidspunktet når objektet oppstod i den virkelige verden';
COMMENT ON COLUMN "administrative_enheter"."kommune"."gyldigtil" IS 'Tidspunktet når objektet opphørte å eksistere i den virkelige verden';
COMMENT ON COLUMN "administrative_enheter"."kommune"."datafangstdato" IS 'dato når objektet siste gang ble registrert/observert/målt i terrenget

Merknad: I mange tilfeller er denne forskjellig fra oppdateringsdato, da registrerte endringer kan bufres i en kortere eller lengre periode før disse legges inn i databasen.
Ved førstegangsregistrering settes Datafangstdato lik førsteDatafangstdato.';
COMMENT ON COLUMN "administrative_enheter"."kommune"."datauttaksdato" IS 'dato for uttak fra en database

Merknad:
Skiller seg fra Kopidato ved at en ikke skiller på om det er uttak fra en originaldatabase eller en kopidatabase.';
COMMENT ON COLUMN "administrative_enheter"."kommune"."opphav" IS 'referanse til opphavsmaterialet, kildematerialet, organisasjons/publiseringskilde

Merknad:
Kan også beskrive navn på person og årsak til oppdatering';
COMMENT ON COLUMN "administrative_enheter"."kommune"."omraade" IS 'den geografiske avgrensingen av stemmekretsen.';
COMMENT ON COLUMN "administrative_enheter"."kommune"."kommunenummer" IS 'nummerering av kommunen i henhold til Statistisk sentralbyrå sin offisielle liste

Merknad: Det presiseres at kommune alltid skal ha 4 siffer, dvs. eventuelt med ledende null. Kommune benyttes for kopling mot en rekke andre registre som også benytter 4 siffer.

Kodeliste: https://register.geonorge.no/sosi-kodelister/inndelinger/inndelingsbase/kommunenummer';
COMMENT ON COLUMN "administrative_enheter"."kommune"."kommunenavn" IS 'Offisielt navn på en kommune. Merk: Hvis kommunen har flere vedtatte parallellnavn, framstår disse i en sammenhengende tekststreng.';
COMMENT ON COLUMN "administrative_enheter"."kommune"."samiskforvaltningsomraade" IS 'angir om kommunen er en del ac samisk forvaltningaområde';
COMMENT ON TABLE "administrative_enheter"."grense" IS 'Generell avgrensingslinje';
COMMENT ON COLUMN "administrative_enheter"."grense"."identifikasjon_lokalid" IS 'lokal identifikator av et objekt

Merknad: Det er dataleverandørens ansvar å sørge for at den lokale identifikatoren er unik innenfor navnerommet.';
COMMENT ON COLUMN "administrative_enheter"."grense"."identifikasjon_navnerom" IS 'navnerom som unikt identifiserer datakilden til et objekt, anbefales å være en http-URI

Eksempel: http://data.geonorge.no/SentraltStedsnavnsregister/1.0

Merknad : Verdien for navnerom vil eies av den dataprodusent som har ansvar for de unike identifikatorene og må være registrert i data.geonorge.no eller data.norge.no';
COMMENT ON COLUMN "administrative_enheter"."grense"."identifikasjon_versjonid" IS 'identifikasjon av en spesiell versjon av et geografisk objekt (instans)';
COMMENT ON COLUMN "administrative_enheter"."grense"."oppdateringsdato" IS 'tidspunkt for siste endring på objektet

Merknad:
Oppdateringsdato kan være forskjellig fra datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).';
COMMENT ON COLUMN "administrative_enheter"."grense"."gyldigfra" IS 'Tidspunktet når objektet oppstod i den virkelige verden';
COMMENT ON COLUMN "administrative_enheter"."grense"."gyldigtil" IS 'Tidspunktet når objektet opphørte å eksistere i den virkelige verden';
COMMENT ON COLUMN "administrative_enheter"."grense"."datafangstdato" IS 'dato når objektet siste gang ble registrert/observert/målt i terrenget

Merknad: I mange tilfeller er denne forskjellig fra oppdateringsdato, da registrerte endringer kan bufres i en kortere eller lengre periode før disse legges inn i databasen.
Ved førstegangsregistrering settes Datafangstdato lik førsteDatafangstdato.';
COMMENT ON COLUMN "administrative_enheter"."grense"."kvalitet_maalemetode" IS 'metode for måling i grunnriss (x,y), og høyde (z) når metoden er den samme som ved måling i grunnriss

Kodeliste: https://register.geonorge.no/sosi-kodelister/generelle-konsepter/4.5/m%C3%A5lemetodekode';
COMMENT ON COLUMN "administrative_enheter"."grense"."kvalitet_noeyaktighet" IS 'punktstandardavviket i grunnriss for punkter samt tverravvik for linjer

Merknad:
Oppgitt i cm';
COMMENT ON COLUMN "administrative_enheter"."grense"."datauttaksdato" IS 'dato for uttak fra en database

Merknad:
Skiller seg fra Kopidato ved at en ikke skiller på om det er uttak fra en originaldatabase eller en kopidatabase.';
COMMENT ON COLUMN "administrative_enheter"."grense"."opphav" IS 'referanse til opphavsmaterialet, kildematerialet, organisasjons/publiseringskilde

Merknad:
Kan også beskrive navn på person og årsak til oppdatering';
COMMENT ON COLUMN "administrative_enheter"."grense"."grense" IS 'Geometri for avgrensingslinjer';
COMMENT ON COLUMN "administrative_enheter"."grense"."avgrensningstype" IS 'angir type avgreisningslinje. Ulike objekter avgrenses av ulike typer grenser.';
COMMENT ON TABLE "administrative_enheter"."fylke" IS 'administrativ inndeling av nasjonen på regionalt nivå

Merknad: Tilsvarer NUTS 3 på internasjonalt statistisk nivå';
COMMENT ON COLUMN "administrative_enheter"."fylke"."identifikasjon_lokalid" IS 'lokal identifikator av et objekt

Merknad: Det er dataleverandørens ansvar å sørge for at den lokale identifikatoren er unik innenfor navnerommet.';
COMMENT ON COLUMN "administrative_enheter"."fylke"."identifikasjon_navnerom" IS 'navnerom som unikt identifiserer datakilden til et objekt, anbefales å være en http-URI

Eksempel: http://data.geonorge.no/SentraltStedsnavnsregister/1.0

Merknad : Verdien for navnerom vil eies av den dataprodusent som har ansvar for de unike identifikatorene og må være registrert i data.geonorge.no eller data.norge.no';
COMMENT ON COLUMN "administrative_enheter"."fylke"."identifikasjon_versjonid" IS 'identifikasjon av en spesiell versjon av et geografisk objekt (instans)';
COMMENT ON COLUMN "administrative_enheter"."fylke"."oppdateringsdato" IS 'tidspunkt for siste endring på objektet

Merknad:
Oppdateringsdato kan være forskjellig fra datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).';
COMMENT ON COLUMN "administrative_enheter"."fylke"."gyldigfra" IS 'Tidspunktet når objektet oppstod i den virkelige verden';
COMMENT ON COLUMN "administrative_enheter"."fylke"."gyldigtil" IS 'Tidspunktet når objektet opphørte å eksistere i den virkelige verden';
COMMENT ON COLUMN "administrative_enheter"."fylke"."datafangstdato" IS 'dato når objektet siste gang ble registrert/observert/målt i terrenget

Merknad: I mange tilfeller er denne forskjellig fra oppdateringsdato, da registrerte endringer kan bufres i en kortere eller lengre periode før disse legges inn i databasen.
Ved førstegangsregistrering settes Datafangstdato lik førsteDatafangstdato.';
COMMENT ON COLUMN "administrative_enheter"."fylke"."datauttaksdato" IS 'dato for uttak fra en database

Merknad:
Skiller seg fra Kopidato ved at en ikke skiller på om det er uttak fra en originaldatabase eller en kopidatabase.';
COMMENT ON COLUMN "administrative_enheter"."fylke"."opphav" IS 'referanse til opphavsmaterialet, kildematerialet, organisasjons/publiseringskilde

Merknad:
Kan også beskrive navn på person og årsak til oppdatering';
COMMENT ON COLUMN "administrative_enheter"."fylke"."omraade" IS 'den geografiske avgrensingen av stemmekretsen.';
COMMENT ON COLUMN "administrative_enheter"."fylke"."fylkesnummer" IS 'nummerering av fylker i henhold til Statistisk sentralbyrå sin offisielle liste

Merknad:
Det presiseres at fylkesnummer alltid skal ha 2 sifre, dvs. eventuelt med ledende null. Fylkesnummer benyttes for kopling mot en rekke andre registre som også benytter 2 sifre.

Kodeliste: https://register.geonorge.no/sosi-kodelister/inndelinger/inndelingsbase/fylkesnummer?';
COMMENT ON COLUMN "administrative_enheter"."fylke"."fylkesnavn" IS 'Offisielt navn på et fylke. Merk: Hvis fylket har flere vedtatte parallellnavn, framstår disse i en sammenhengende tekststreng.';
COMMENT ON COLUMN "administrative_enheter"."fylke"."samiskforvaltningsomraade" IS 'angir om fylket er en del ac samisk forvaltningaområde';
COMMENT ON TABLE "administrative_enheter"."kommune_administrativenhetnavn" IS 'offisielt navn på en kommune, et fylke eller en nasjon';
COMMENT ON COLUMN "administrative_enheter"."kommune_administrativenhetnavn"."navn" IS 'navnet på den administrative enheten i angitt språk.';
COMMENT ON COLUMN "administrative_enheter"."kommune_administrativenhetnavn"."spraak" IS 'angir språk for det administrative navnet.';
COMMENT ON COLUMN "administrative_enheter"."kommune_administrativenhetnavn"."rekkefoelge" IS 'angir presentasjonsrekkefølge i sammenstaninger av nav på administretiv enhet ved presentasjon på alle sprøkformer.';
COMMENT ON TABLE "administrative_enheter"."fylke_administrativenhetnavn" IS 'offisielt navn på en kommune, et fylke eller en nasjon';
COMMENT ON COLUMN "administrative_enheter"."fylke_administrativenhetnavn"."navn" IS 'navnet på den administrative enheten i angitt språk.';
COMMENT ON COLUMN "administrative_enheter"."fylke_administrativenhetnavn"."spraak" IS 'angir språk for det administrative navnet.';
COMMENT ON COLUMN "administrative_enheter"."fylke_administrativenhetnavn"."rekkefoelge" IS 'angir presentasjonsrekkefølge i sammenstaninger av nav på administretiv enhet ved presentasjon på alle sprøkformer.';

COMMIT;
